### PR TITLE
Log non-strings into log file like console.log does

### PR DESCRIPTION
**Pull request by mikiher**
This was inspired by #3398, in which the reporter attaches the log file, which doesn't contain a detailed logging of AggregateError.

Examining the Logger, I found that when logging to file and emiting log events to listeners, the log object is built like this:
```js
    const logObj = {
      timestamp: this.timestamp,
      source: src,
      message: args.join(' '),
      levelName: this.getLogLevelString(level),
      level
    }
```

However, `Array.join` calls `toString` on each arg, which, in the case of `Error` args, just returns the name and message of the error, without the stack trace or any additional fields. 

`console.log` on the other hand, uses `util.inspect` on non-string arguments, which returns a more detailed object representation, and also has special handling for Error objects.

I fixed this issue by mimicking how `console.log` builds the message.

I also made a couple of other minor changes:
- Moved the logging logic into a single private method `\#log`
- Before my changes, `fatal` and `note` always logged, regardless of `this.logLevel`, but file logging still checked against `this.logLevel`. I fixed the inconsistency (now file logging also disregards `this.logLevel` for `fatal` and `note`). I didn't know if I should also disregard it for log event emitting? currently left that unchanged.

In addition, I added unit tests for Logger.

### CODE REVIEW

**Comment by mikiher** [comment]
I also needed to resolve a seemingly unrelated flakiness in the BookFinder unit test. 

Not sure exactly what happened there. I modified the test code slightly and it went away (the many changes are due to prettier formatting).

**Comment by mikiher** [comment]
> We can disregard those for the log event emitting also.

OK, I'll fix the code then.

**Comment by mikiher** [comment]
Done. This is ready for review.

**Comment by advplyr** [comment]
Thanks!

**Pull request merged**
