### PR TITLE
Update Server Libraries

### PR DESCRIPTION
**Pull request by lkiesow**
This patch updates the server libraries to their latest state.

### CODE REVIEW

**Comment by lkiesow** [comment]
I didn't use this in production, but I did click through several things in the ui including functions like fetching metadata and cover images (where I guess axios is being used) and didn't see any issues. Do you have anything in particular you would want me to test?

**Comment by advplyr** [comment]
I haven't gone through it yet but axios is used for podcast RSS feeds and fetching data from metadata providers.

**Comment by lkiesow** [comment]
I now got around testing that podcasts also work and not only fetching metadata for books. There seems to be no problem and everything works well.

For Podcasts, I've tested adding new Podcasts via RSS URL as well as searching for Podcasts, searching for episodes, updating and downloading episodes. I didn't detect any problems.

**Comment by advplyr** [comment]
Thanks!

**Comment by lkiesow** [comment]
I'm going to test the RPM auto-updates later today.
If things work there should indicate if this is a general problem.
I'll let you know.

But Docker seems towork at least.

**Pull request merged**
