### PR TITLE
podcast episode number & accessibility improvements

### PR DESCRIPTION
**Pull request by jflattery**
Add episode number to list group view

### CODE REVIEW

**Comment by jflattery** [comment]
Accessibility Labels as suggested by @duplaja

**Comment by jflattery** [comment]
Docker image is currently building and will be available at `jflattery/abs-dev:accessibility`

**Comment by advplyr** [comment]
much obliged

**Comment by duplaja** [comment]
@jflattery  Thank you, I appreciate it! That does look much cleaner / much closer to what I'm used to doing for these.  I wasn't sure if there was anything particular to the framework, so I had initially just changed what it was currently pulling the label from (icon text).

Again, coming from a non-framework background, there were a few other accessibility items I noted in #441, but don't (currently) have the background to tackle. If you feel up to taking a look, or can give me some pointers for where to start looking, I would appreciate it! (if you have the time and inclination, of course)

**Pull request merged**
