### PR TITLE
Update Login Page with Logo and Input Form Styling

### LINKED ISSUE #2682: [Enhancement]: audiobookshelf logo or name on the login screen
### Describe the feature/enhancement

It was pointed out on discord that the login page has not identification to tell you what you’re logging in to. 

It might be nice to have text or the ABS logo on this page by the “Login” heading. 

IMG_1595

### PR DESCRIPTION
**Pull request by mfcar**
This pull request updates the login page with a logo and an input form box to create a distinction between the login form and the main background. Feedback is appreciated.

Fixes #2682

Screenshot 2024-02-28 at 19 23 44

### CODE REVIEW

**Comment by gh0sti** [comment]
I could have sworn there was one before.

**Comment by TeroKeso** [comment]
Hi,

have you tried how this looks on mobile format?

**Comment by gh0sti** [comment]
This can merged then right?

**Comment by advplyr** [comment]
Thanks I prefer a smaller logo image and in playing with it I ended up putting it in the top-left in the same position it is in Appbar.vue

desktop
image

mobile
image

There is an existing bug I spotted on mobile landscape but don't have the time to handle that now. It's cosmetic so won't interfere with usability.

**Pull request merged**
