### PR TITLE
Add: Force re-scan library

### PR DESCRIPTION
**Pull request by igorkaldowski**
Added a force rescan button to the library settings page.

### CODE REVIEW

**Comment by advplyr** [comment]
In testing I found some other bugs. There is another one which is the force rescan is always detecting an update when there isn't one. I'm looking into that now.
Also, I want to think of a way a different place for the force re-scan button. For large libraries over an SMB share the force re-scan could take a long time.

**Comment by advplyr** [comment]
The `rescanAudiobook` method was assuming that the audiobook has updates. I changed that function to return null if no updates were made so they don't get recorded as updates.
Existing audio files were not getting re-scanned either. My understanding of the forceRescan flag is that it will probe every audio file again, which would pickup on changed ID3 tags for example. I updated the method to first re-scan existing audio files.

**Comment by igorkaldowski** [comment]
I wanted it to also rescan other files like opf files in case of changes because the current scan ignores them.

**Comment by igorkaldowski** [comment]
That's perfect. I mainly wanted it to rescan opf files for changes. 
One way to make it faster for large libraries would be to store the date of when the file was last scanned then compare it to the date modified before doing anything. 
The only thing I can think to add is a way to stop manually edited fields in books from being changed. Similar to how you can lock fields in plex.

**Comment by advplyr** [comment]
This is released in `v1.6.36`. I added a note explaining the force re-scan under the libraries table until there is a better design for that button.
Agree on the last modified date on file should be checked, it should also be stored on the audiobook so it can be used as a sort.

**Pull request merged**
