### PR TITLE
Translation strings added

### PR DESCRIPTION
**Pull request by nichwall**
Fixes https://github.com/advplyr/audiobookshelf/issues/3242

This PR updates the strings in the client mentioned in the above issue, as well as updating other strings in those files which were not translatable.

This PR does *not* update the task strings which are generated/updated by the server because right now only the client has i18n functionality. I opened https://github.com/advplyr/audiobookshelf/issues/3303 to track this separately.

### CODE REVIEW

**Comment by nichwall** [comment]
Got some more strings translated. I also cleaned up a few similar strings that were already in the translation files.

This PR should be good to merge. There are about 100 toast strings left based on the number of search results, but it will probably be a few days before I get to them so I can open a new PR for those.

**Comment by nichwall** [comment]
Okay, I'll stop editing the strings here. There are still about 50 more toast messages remaining, but this PR just kept getting longer. More similar strings were combined.

Most of the remaining strings are related to podcast episodes and are not all in toasts, so that will take a bit to go through the files and update everything.

**Comment by advplyr** [comment]
Thanks! I wanted to remove a lot of those success toasts because it is redundant when the change can be seen.
Most of the "failed to get.." error toasts can be consolidated in the generic failed to load toast. There is always a more specific console log in the rare case it has to be distinguished.

**Comment by nichwall** [comment]
Makes sense, thanks for cleaning those up.

**Pull request merged**
