### PR TITLE
Add published decade filter option

### LINKED ISSUE #3448: [Enhancement]: "Published > Decade" filter option
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

I'm trying to avoid asking for "smart collections," something I have in Plex I use to group my audiobooks like this:
image
Instead, I think I might get by with an additional Filter for "Published > Decade ####" where #### is a decade like 1840 or 1970 or 2020. 

### Why would this be helpful?

It would--to an extent--replace functionality I'm losing in migrating from Plex.

### Future Implementation (Screenshot)

image
image

### Audiobookshelf Server Version

v2.13.4

### Current Implementation (Screenshot)

_No response_

### PR DESCRIPTION
**Pull request by glorenzen**
This adds a library filter option for Published Decade and resolves #3448 

It doesn't follow the same format as the images in the issue, but I thought "Published Decade" was more descriptive and user-friendly than just "Published" in the top list with "Decade XXXX" in the sublist.

Everything seems to be working on my end, but there may be something I'm missing.

image

image

### CODE REVIEW

**Comment by advplyr** [comment]
Working great, nice and clean, thanks!

The projects formatting options are setup for vscode and should automatically remove semicolons on save. If you're not using vscode the .prettierrc and .editorconfig files might be able to work with your code editor to auto apply our formatting settings.

**Comment by glorenzen** [comment]
I am using VS Code, so that's weird it didn't remove the semicolons automatically. I'll have to check that there isn't something that I misconfigured.

**Comment by pwinnski** [comment]
Thank you, @glorenzen! I totally agree that your solution is better than my proposal. I wasn't sure how "Published Decade" would look with all the other single-word items in that last, but I clearly chose poorly, as it looks great!

**Comment by pwinnski** [comment]
Minor nit, I have a single book for which the published year is `0400`, and while `400` appears as an option in the Published Decade list, selecting that option tells me there are no matches, so apparently it doesn't like the three-digit year.
Still, this is great!

**Comment by glorenzen** [comment]
@pwinnski I just opened a new pull request with a fix for the issue you're having: #3518

**Pull request merged**
