### PR TITLE
Format the progress info into a table

### PR DESCRIPTION
**Pull request by faush01**
This change formats the progress information into a row structure so it is easier to read and is more consistent with the page layout.

I also change the confirmation question to use the internal app dialogue instead of the browser native one.
And moved some of the text to strings resources

All the existing logic for what and when it is shown is the same, it is just come clean up and formatting changes. 

Before Changes
image

After Changes
image

### CODE REVIEW

**Comment by nichwall** [comment]
I personally like the current progress bubble because it fits with the "play and read buttons" right below it, but for the sake of discussion my thoughts are below.

The progress should still be near the "play" button so it is in context with where it's used (pressing play or read to continue the media).

We may want to change up the column order so there isn't a large gap between progress and start date for ebook-only items. The current implementation looks like this, with just the progress and started date. There is a discussion somewhere about showing progress individually for both an ebook and an audiobook, but I'm can't find it right now.
image

However, the table could make viewing progress of other users easier (if sharing progress with other users is implemented).
https://github.com/advplyr/audiobookshelf/issues/375
https://github.com/advplyr/audiobookshelf/issues/3172

**Comment by advplyr** [comment]
I also prefer the progress bubble but it could be that I'm just used to it.

**Comment by faush01** [comment]
Yes UX preference is a tricky thing. 
Just to be clear I am not a fan of the bubble, I feel it is out of place on the page and interrupts visual flow.

I started off this trying to add current position to the position info and the bubble but the bubble then got bigger and that looked even more out of place. So I started experimenting with different approaches of displaying this info, the table felt like the best and fit with the page flow the best.

I also thought of an option to have the current position info added to the metadata at the top in the table (Option 1) in the screenshot. I moved the table of position into the just under the play button (Option 3) and also tried just adding the current position to the bubble (Option 2).

Here is a screenshot with some options.
If you don't like any of them that if cool, UX is very subjective and sometimes what you are used to is comfortable.

image

**Comment by advplyr** [comment]
I'm not a fan of storing the progress info with the metadata because it is mixing user-specific data with the metadata.
I haven't had the need to see the current time there.
A lot of the UI/UX came from other users suggestions over the years. I'm not stuck on any particular design.

**Comment by faush01** [comment]
> I'm not a fan of storing the progress info with the metadata because it is mixing user-specific data with the metadata.
Sorry I was unclear, not storing, just displaying it with the other metadata at the top, as shown in option 1 in the screenshot. That change does not require any storage changes, it is just some layout vue code changes.
> A lot of the UI/UX came from other users suggestions over the years. I'm not stuck on any particular design.
Yeah UI/UX is a very personal thing, there are some good rules of best practice but a lot of it comes down to what looks good or works for people and because people are diverse that is hard to cover everyone.
Overall I love the design and layout, its just the progress bubble, it looks so out off place to my eye, but again that is in my opinion.

**Pull request closed without merging**
