### PR TITLE
Invert Tag Selection

### LINKED ISSUE #1545: [Enhancement]: Ability to deny user access to chosen tag(s)
### Describe the feature/enhancement

Currently admins can limit a user's access to a specific tag or tags. I would like to be able to allow general access _except for_ a chosen tag or tags.

### PR DESCRIPTION
**Pull request by divyangbw**
Fixes #1545
Feel free to suggested UI changes as well

## Changes
Updates:
- Removed Libraries to keep this simple for now

Support for:
* Tags NOT Accessible to User
* Renamed `itemTagsAccessible` to `itemTagsSelected`.

UI & UX Changes:
* Allow the modal to scroll
* New Invert options to chose if the list is for access or prevent access.

Screenshot 2023-04-27 at 4 39 59 PM

Issues:
- #1545
- Partially #402

### CODE REVIEW

**Comment by advplyr** [comment]
An issue with this method is that if you do the invert then add more tags to the library it would need to continually keep updating the `itemTagsAccessible` array or else those users won't have access to anything with new tags.

Also, if someone has thousands of tags then we would be increasing the payload of a user by a notable amount.

**Comment by divyangbw** [comment]
Hmm, true. Guessing this holds true even now though, right? Anytime a new tag is added, the admin would need to go in add access to each user? Also I guess no one will go ahead and add a thousand tags to begin with, but if they ever did, the payload problem would happen even now?

Could go and create 2 separate arrays (boolean clears one or the other on save) or maybe better, use the invert boolean to determine if user has access. So rather than `itemTagsAccessible`, we make it `itemTagsSelected`, and the boolean determines if its for access or not access. Problem with both of these approaches is that we are essentially changing the way the core permissions would work...not sure how that effects mobile, for example.

Do you have a strategy in place for something like this? I'm not sure I'd have the time to touch the mobile app right now.

**Comment by advplyr** [comment]
Ugh, I had typed a whole nice response to you then my browser randomly closed.

I think the best approach is what you said about using `itemTagsSelected`. This will not impact the mobile clients at all because these permissions are only used by the API to determine whether it should return an item to the user or not.

Every API that is returning library items will call `checkCanAccessLibraryItemWithTags` function in `User.js` to check if the user has access. That should be the only place as far as permissions go that needs to be updated. The rest is just UI and the `update` function in `User.js`

**Comment by apiweb** [comment]
I have a suggestion regarding the option to invert the selection on GitHub. Instead of just having the option to invert the selection, it would be great if we could have both an allow and deny list. This would be especially useful in cases where we only want to allow certain libraries or deny certain access.

Having both lists would make it much easier to manage compared to having to invert the selection constantly. This would also solve the issue of updating the list every time a new library is added, as users can simply add the new library/tag to the allow/deny list themselves.

**Comment by divyangbw** [comment]
@apiweb With the changes I'm making, there's always a single list to maintain -- has access to X tags OR doesn't have access to X tags. That means, we no longer need to update the list every time a new tag. So if I block access to the tag `Adult`, the user will just get access to everything (including any new tags that are added) except `Adult.

I'll be removing the Library related changes for now to keep this simple. I'm confused by `having to invert the selection constantly`...how so? When creating/updating your user, you're simply deciding if you wish to give per tag access or block per tag access. Same toggle as give access to everything.

**Comment by advplyr** [comment]
Thanks! This is working well

**Pull request merged**
