### PR TITLE
Add Hebrew translation json and Hebrew to i18n.js

### PR DESCRIPTION
**Pull request by arcmagedr**
Add Hebrew translation json and Hebrew to i18n.js

### CODE REVIEW

**Comment by advplyr** [comment]
@mikiher I guess that checkout action isn't going to work with PRs

**Comment by mikiher** [comment]
Darn, sorry, I'll fix this ASAP

**Comment by advplyr** [comment]
No rush, thanks!

**Comment by arcmagedr** [comment]
I've gone over all the translation and verified everything makes sense, at least in the context of the file itself.
Once merged, if anything will need changing I'll update as necessary.

One thing though, is there handling for right-to-left languages? Is there anything else that needs to be done in that regard?

**Comment by nichwall** [comment]
I don't think anything has been done for right to left languages. Looks like at a minimum the `dir` tag would need to be added everywhere a string shows up. Not sure if there's anything else that needs to be done for that.

https://www.w3.org/International/questions/qa-html-dir

**Comment by advplyr** [comment]
Thanks! Yeah we will have to setup for rtl languages still

**Pull request merged**
