### PR TITLE
Get more data from opf

### PR DESCRIPTION
**Pull request by igorkaldowski**
When there is html in the description on a opf file it will strip it rather than not returning. It also gets series and volume number from the opf.

### CODE REVIEW

**Comment by Helico-Pter** [comment]
I was just thinking it would be great if 'series' could be read from the file.

**Comment by advplyr** [comment]
Thanks, I had been meaning to eventually use the strip html package there.

Can you move this meta check https://github.com/advplyr/audiobookshelf/pull/218/commits/6e621ecce163247b395f7af4bcbc0ca6250c174a#diff-3ddb151b8ce6aa69c5d2527e033c0aac28a2c4873111ffb0948fa37bb951fbe1R59
into the parseOpfMetadataXML function instead of xmlToJson. xmlToJson might eventualy be used for something other than Opf files.

**Comment by igorkaldowski** [comment]
Done. I also change the series page to sort alphabetically and on the series pages to sort by volume number as a number not alphabetically.

**Comment by advplyr** [comment]
This is released in `v1.6.35`

**Pull request merged**
