### PR TITLE
PR Template

### PR DESCRIPTION
**Pull request by nichwall**
## Brief summary
This PR adds a PR template to the repository for new PRs. There is not an associated issue.

## In-depth Description
This PR sets up the text input for PRs using the template to improve the quality and standardize the format of PRs. Unlike the issue templates which are able to have distinct text boxes and dropdowns, the PR template support on GitHub only seems to allow for a single PR template that is pasted into the text box.

## How have you tested this?
Experimentation in a test repo.

## Screenshots
image

### CODE REVIEW

**Comment by mikiher** [comment]
This looks good as a first step. A couple of suggestions:
- Add somthing about passing all checks
- Add an optional `Fixes # ` section

**Comment by advplyr** [comment]
For users who haven't had a PR approved yet the checks won't run until they are manually approved

**Comment by nichwall** [comment]
Thanks for the feedback. I can add a blurb about passing checks and that they won't run until approved. I think the checks can run in forks though, so they could still check that the checks pass in their fork to reduce the chance of needing to change something after it's reviewed.

**Comment by advplyr** [comment]
Thanks!

**Pull request merged**
