### PR TITLE
Add: OPF file supports multiple series as sequence of : calibre:series and calibre:series_index; including tests

### PR DESCRIPTION
**Pull request by jedrus2000**
I see that some people like me using this software are missing multiple series in OPF file.

```xml
<meta name="calibre:series" content="Serie 1"/>
<meta name="calibre:series_index" content="1"/>
<meta name="calibre:series" content="Serie 2"/>
<meta name="calibre:series_index" content="2"/>
```

so here it is, along with unit tests.

### CODE REVIEW

**Comment by advplyr** [comment]
I updated this to handle the case where the series content is empty:
```xml
<meta name="calibre:series" content=""/>
```
I added a test for that and a test for namespace.

Thanks!

**Comment by sydlexius** [comment]
I was unaware that OPF supported multiple series.  What's a good way to manage the metadata for books belonging to > 1 series?

**Comment by bwalocha** [comment]
Does not work for me, the Series and Narratros are not filled:

image

`
<?xml version="1.0" encoding="utf-8"?>
<ns0:package xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:ns0="http://www.idpf.org/2007/opf" unique-identifier="BookId" version="2.0">
  <ns0:metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
    <dc:title>{TITLE}</dc:title>
    <dc:subtitle>{SUBTITLE}</dc:subtitle>
    
    <dc:creator opf:role="aut">{AUTHOR_001}</dc:creator>
    <dc:creator opf:role="aut">{AUTHOR_002}</dc:creator>
	<dc:creator opf:role="aut">{AUTHOR_003}</dc:creator>
    
	<dc:date>2020</dc:date>
    
	
	<ns0:meta name="calibre:series" content="La Faucheuse" />
    <ns0:meta name="calibre:series_index" content="2" />
	<ns0:meta name="calibre:series" content="Trylogia husycka" />
	<ns0:meta name="calibre:series_index" content="1" />
	
	<dc:description>{DESCRIPTION}</dc:description>
	
	<dc:subject>{GENRE_001}</dc:subject>
	<dc:subject>{GENRE_002}</dc:subject>
	<dc:subject>{GENRE_003}</dc:subject>
	<dc:tag>{TAG_001}</dc:tag>
	<dc:tag>{TAG_002}</dc:tag>
	<dc:tag>{TAG_003}</dc:tag>

	
    <dc:creator opf:role="nrt">{NARRATOR_001}</dc:creator>
    <dc:creator opf:role="nrt">{NARRATOR_002}</dc:creator>
    <dc:creator opf:role="nrt">{NARRATOR_003}</dc:creator>
	<dc:creator ns0:role="nrt">{NARRATOR_004}</dc:creator>
	
    <dc:identifier opf:scheme="ISBN">{ISBN}</dc:identifier>
    <dc:identifier opf:scheme="ASIN">{ASIN}</dc:identifier>

	<dc:publisher>{PUBLISHER}</dc:publisher>
	<dc:language>{LANGUAGE}</dc:language>
	
	
  </ns0:metadata>
</ns0:package>
`

**Comment by nichwall** [comment]
> Does not work for me, the Series and Narrators are not filled:
> 
> image
> 
> image
> 

Your best bet is to open an issue. This PR is from 9 months ago

**Pull request merged**
