### PR TITLE
Clear selectedEpisodes on download.  

### LINKED ISSUE #931: [Bug]: [Podcasts][Find Episodes] Downloaded Episodes Remain Selected Post-Download, Results In Unnecessary Extra Downloads
### Describe the issue

This is a bug in the Find Episodes dialog that comes up when you click the Find Episodes button from within any podcast in the library.  It looks like the logic for when finishing the batch download isn't clearing out everything at the end like it needs to. Also there's no check for an existing file before a download is done?

### Steps to reproduce the issue

1. open a podcast where you have episodes left to download
2. open Find Episodes
3. Click the checkbox on 1 or more episodes and then click "Download # Episode(s)" button
4. open Find Episodes again
5. the "Download # Episode(s)" button is now stuck with the count of all currently downloaded episodes. If clicked, all episodes will be re-downloaded again

To escape this condition you must refresh the page.

### Audiobookshelf version

2.1.4

### How are you running audiobookshelf?

Docker

### PR DESCRIPTION
**Pull request by barrycarey**
Clears the selectedEpisodes once the download is started.  Fixes #931.  

Also, clicking on the checkbox for existing downloads still added that item to the list.  Moved onClick to checkbox instead of container div to prevent this.

### CODE REVIEW

**Comment by barrycarey** [comment]
Idiot move on my part making a PR 10 minute after looking at the code for the first time.  Will reopen tomorrow with a proper fix.

**Comment by advplyr** [comment]
I'm looking through this modal and it is a mess so I'm going to make some more updates in your PR. I also think the toggle shouldn't requiring clicking the checkbox.

**Comment by barrycarey** [comment]
Sounds good. 

As for the toggle, do you mean it should active by clicking clicking anywhere on the line? 

Also, the setting of selected episodes in the init seems unnecessary.

**Comment by advplyr** [comment]
Yeah that's what I mean and yeah the init is unnecessary. I'm going to do a refactor now

**Pull request merged**
