### PR TITLE
Update Bookfinder.js : getAudibleResults : remove (unabridged)

### PR DESCRIPTION
**Pull request by sxb1n9**
cleantitle for search in audible as (unabridged) doesn't find anything

### CODE REVIEW

**Comment by advplyr** [comment]
If a book had parenthesis in the title then this would filter that out.
This feels like a workaround to your specific issue with how your audiobook was titled.

**Comment by sxb1n9** [comment]
Almost all of my audiobooks from audible have (unabridged) in the title.   I did not edit them at all and downloaded them and converted using https://github.com/audiamus/BookLibConnect

They come directly from that program into a folder for AudioBookShelf.

**Comment by samosbor** [comment]
I think this a good idea and I found that a bunch of my audiobooks had (unabridged) in the title. 

I do agree that the regex is too broad though. It should probably just be a case-insensitive check for (unabridged).

Even better: add a new setting for filtering certain terms in the title match.

**Comment by samosbor** [comment]
Thanks for this good idea @sxb1n9. I was able to incorporate a fix for this here https://github.com/advplyr/audiobookshelf/pull/735

**Comment by advplyr** [comment]
#735 was merged

**Pull request closed without merging**
