### PR TITLE
Update material icons

### PR DESCRIPTION
**Pull request by glorenzen**
This pull request adds font files for Material Symbols to replace the Material Icons fonts, which are deprecated.

The Material Icons files and classes are still there, but I have added new Material Symbols font files and replaced all material-icons CSS classes with new material-symbols classes.

### CODE REVIEW

**Comment by advplyr** [comment]
Thanks this is a nice update. The YearInReview components also use material icons in canvas. It should be able to get updated the same way

**Comment by glorenzen** [comment]
Awesome, I just updated the YearInReview components and a couple of others that I missed. That should be all of them now.

**Comment by glorenzen** [comment]
I know this hasn't been open for very long, but would it be possible to have this reviewed/merged soon? I'd like to use a few of the Material Symbols in my other PR #3113 :)

**Comment by mfcar** [comment]
I think it would be nice to add the link for the icon set in the README or the contributing pages.
For the old icon set, I always forgot the set name and struggled to find the link for the gallery.

**Comment by glorenzen** [comment]
@mfcar Do you mean add this link to the Contributing section at the end of the README? https://fonts.google.com/icons

**Comment by advplyr** [comment]
Great, thanks!

**Pull request merged**
